
default_stages: [pre-push]
repos:
  - repo: https://github.com/crate-ci/typos
    rev: v1.34.0
    hooks:
      - id: typos

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: uv run ruff check --force-exclude
        language: system
        types: [python]
        require_serial: true
      - id: ruff-format
        name: ruff-format
        entry: uv run ruff format
        language: system
        types: [python]
        require_serial: true
      - id: pyright
        name: pyright
        entry: uv run pyright
        pass_filenames: false
        language: system
        types: [python]
      - id: test
        name: test
        entry: uv run pytest
        pass_filenames: false
        language: system
        types: [python]